{# Conda-forge recipe for Agent ROS Bridge #}
{# The SHA256 is automatically updated by conda-forge's bot on release #}
{# To update manually: wget -qO- <url> | sha256sum #}
{% set name = "agent-ros-bridge" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # NOTE: SHA256 will be auto-populated by conda-forge's bot on release
  sha256: 0000000000000000000000000000000000000000000000000000

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - agent-ros-bridge = agent_ros_bridge.mcp:main
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - ros-humble-rclpy  # [unix]
  run_constrained:
    - mcp >=1.0.0
    - websockets >=10.0
    - grpcio >=1.50.0
    - aiohttp >=3.8.0
    - pyyaml >=6.0

test:
  imports:
    - agent_ros_bridge
  commands:
    - python -c "from agent_ros_bridge import ROSBridge; print('OK')"
  requires:
    - pip

about:
  home: https://github.com/webthree549-bot/agent-ros-bridge
  summary: 'Connect AI agents to ROS1/2 robots via MCP, WebSocket, and gRPC'
  description: |
    Agent ROS Bridge is a secure, multi-agent bridge for ROS1/2 robot control.
    Connect AI agents like Claude Desktop to ROS robots via the Model Context
    Protocol (MCP), WebSocket, or gRPC.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://docs.openclaw.ai/agent-ros-bridge
  dev_url: https://github.com/webthree549-bot/agent-ros-bridge

extra:
  recipe-maintainers:
    - openclaw
