name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it!
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What should happen?
      placeholder: It would be great if...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What else did you try?
      placeholder: I considered X but it doesn't work because...
  
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Who would benefit and how?
      placeholder: This would help robotics researchers who...
    validations:
      required: true
  
  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I am willing to implement this feature
        - label: I can provide testing/feedback
