FROM osrf/ros:noetic-desktop-full
WORKDIR /app
ENV ROS_TYPE=ros1
ENV ROS_DISTRO=noetic
COPY . /app
RUN pip3 install -r requirements.txt
RUN chmod +x scripts/*.sh
RUN ./scripts/build.sh
ENTRYPOINT ["/app/docker/docker-entrypoint.sh"]
CMD ["/bin/bash"]