"""Bridge Protocol Buffer Definitions (Python module).

This module provides protobuf-compatible classes for gRPC communication.
In a production setup, this would be generated from a .proto file using protoc.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Header:
    """Message header with metadata."""

    message_id: str = ""
    timestamp: int = 0
    client_id: str = ""


@dataclass
class Command:
    """Command message."""

    action: str = ""
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass
class CommandResponse:
    """Command response message."""

    success: bool = False
    data: str = ""
    error: str = ""


@dataclass
class Telemetry:
    """Telemetry data message."""

    topic: str = ""
    data: dict[str, Any] = field(default_factory=dict)


@dataclass
class Event:
    """Event message."""

    event_type: str = ""
    source: str = ""
    data: dict[str, Any] = field(default_factory=dict)


@dataclass
class Status:
    """Status message."""

    healthy: bool = False
    uptime_seconds: int = 0
    version: str = ""


# gRPC Service registration functions
# These would normally be generated by protoc


def add_BridgeServiceServicer_to_server(servicer, server):
    """Register BridgeService servicer to gRPC server.

    Args:
        servicer: The servicer implementation
        server: The gRPC server
    """
    # This is a stub - real implementation would register RPC handlers
    pass


def add_BridgeServiceServicer_to_server(servicer, server):
    """Register BridgeService servicer to gRPC server.

    Args:
        servicer: The servicer implementation
        server: The gRPC server
    """
    # In real implementation, this would add the service to the server
    if hasattr(server, "add_servicer"):
        server.add_servicer(servicer)


# For compatibility with generated protobuf code
class BridgeServiceServicer:
    """Base class for BridgeService servicer."""

    async def SendCommand(self, request, context):
        """Handle SendCommand RPC."""
        raise NotImplementedError()

    async def HealthCheck(self, request, context):
        """Handle HealthCheck RPC."""
        raise NotImplementedError()

    async def SubscribeTelemetry(self, request, context):
        """Handle SubscribeTelemetry RPC."""
        raise NotImplementedError()

    async def SubscribeEvents(self, request, context):
        """Handle SubscribeEvents RPC."""
        raise NotImplementedError()

    async def StreamCommands(self, request_iterator, context):
        """Handle bidirectional StreamCommands RPC."""
        raise NotImplementedError()


class BridgeServiceStub:
    """Client stub for BridgeService."""

    def __init__(self, channel):
        self.channel = channel

    async def SendCommand(self, request):
        """Send command to server."""
        raise NotImplementedError()

    async def HealthCheck(self, request):
        """Check server health."""
        raise NotImplementedError()


# Message type references for compatibility
DESCRIPTOR = None  # Would be set by protoc


# Empty message for void requests/responses
class Empty:
    """Empty message."""

    pass
