# Homebrew formula for Agent ROS Bridge
# 
# Installation:
#   brew tap openclaw/tap
#   brew install agent-ros-bridge
#
# To update this formula on release:
#   brew bump-formula-pr --url=<new_tarball_url> openclaw/tap/agent-ros-bridge
#
# The SHA256 will be computed automatically by bump-formula-pr

class AgentRosBridge < Formula
  desc "Connect AI agents to ROS1/2 robots via MCP, WebSocket, and gRPC"
  homepage "https://github.com/openclaw/agent-ros-bridge"
  url "https://github.com/openclaw/agent-ros-bridge/archive/refs/tags/v0.4.0.tar.gz"
  # NOTE: SHA256 computed automatically by `brew bump-formula-pr` on release
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "Apache-2.0"
  head "https://github.com/openclaw/agent-ros-bridge.git", branch: "main"

  depends_on "python@3.11"
  depends_on "openssl@3"
  
  # Optional dependencies based on usage
  option "with-mcp", "Enable MCP (Model Context Protocol) support for Claude Desktop"
  option "with-websocket", "Enable WebSocket transport"
  option "with-grpc", "Enable gRPC transport"
  option "with-openclaw", "Enable OpenClaw cloud integration"
  option "with-all", "Enable all optional features"

  # Python resources are auto-generated by `brew update-python-resources`
  # during the formula update process. The following are placeholders.
  resource "mcp" do
    url "https://files.pythonhosted.org/packages/source/m/mcp/mcp-1.0.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "websockets" do
    url "https://files.pythonhosted.org/packages/source/w/websockets/websockets-10.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "grpcio" do
    url "https://files.pythonhosted.org/packages/source/g/grpcio/grpcio-1.50.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  resource "aiohttp" do
    url "https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.8.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  def install
    ENV["PIP_NO_CACHE_DIR"] = "1"
    
    # Create virtual environment
    venv = virtualenv_create(libexec, "python3.11")
    
    # Install main package
    venv.pip_install_and_link buildpath
    
    # Install optional dependencies based on options
    if build.with?("mcp") || build.with?("all")
      venv.pip_install resource("mcp")
    end
    
    if build.with?("websocket") || build.with?("all")
      venv.pip_install resource("websockets")
    end
    
    if build.with?("grpc") || build.with?("all")
      venv.pip_install resource("grpcio")
    end
    
    if build.with?("openclaw") || build.with?("all")
      venv.pip_install resource("aiohttp")
    end
    
    # Install entry point
    bin.install_symlink libexec/"bin/agent-ros-bridge"
  end

  def post_install
    # Create config directory
    (etc/"agent-ros-bridge").mkpath
    
    # Install example config if not present
    unless (etc/"agent-ros-bridge/bridge.yaml").exist?
      (etc/"agent-ros-bridge").install "config/bridge.yaml.example" => "bridge.yaml"
    end
  end

  service do
    run [opt_bin/"agent-ros-bridge", "--config", etc/"agent-ros-bridge/bridge.yaml"]
    keep_alive true
    log_path var/"log/agent-ros-bridge.log"
    error_log_path var/"log/agent-ros-bridge.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    # Test basic import
    system libexec/"bin/python", "-c", "from agent_ros_bridge import ROSBridge; print('OK')"
    
    # Test CLI
    assert_match "agent-ros-bridge", shell_output("#{bin}/agent-ros-bridge --help")
  end
end
