#!/usr/bin/env python3
"""
Production Configuration Generator

Interactive tool to generate production-ready safety configuration.
Ensures ISO 10218 compliance and proper safety analysis.

Usage:
    python scripts/generate_producticon_config.py [--output config.yaml]

Features:
    - Interactive robot specification input
    - ISO 10218 compliance checks
    - Safety zone visualization
    - Risk assessment guidance
"""

import argparse
import json
import math
from dataclasses import dataclass, field
from typing import Any

import yaml


@dataclass
class RobotSpecification:
    """Robot specification from user input"""
    
    name: str = ""
    robot_type: str = "mobile_robot"  # mobile_robot, manipulator, drone, humanoid
    max_linear_velocity: float = 0.0  # m/s
    max_angular_velocity: float = 0.0  # rad/s
    max_acceleration: float = 0.0  # m/s^2
    max_deceleration: float = 0.0  # m/s^2
    mass: float = 0.0  # kg
    dimensions: dict[str, float] = field(default_factory=dict)  # length, width, height in meters
    sensor_types: list[str] = field(default_factory=list)
    workspace_type: str = "indoor"  # indoor, outdoor, mixed
    human_proximity: str = "collaborative"  # separated, collaborative, hand_guided
    application: str = ""  # description
    safety_plc: bool = False
    hardware_estop: bool = False
    light_curtains: bool = False
    force_limiting: bool = False


@dataclass
class SafetyZone:
    """Defined safety zone"""
    
    name: str
    zone_type: str  # restricted, warning, collaborative
    bounds: list[dict[str, float]]
    reason: str


@dataclass
class SafetyConfig:
    """Generated safety configuration"""
    
    robot_id: str
    specification: RobotSpecification
    limits: dict[str, Any]
    zones: list[SafetyZone]
    compliance_notes: list[str]
    warnings: list[str]
    
    def to_yaml(self) -> str:
        """Convert to YAML format"""
        data = {
            "# Production Safety Configuration": None,
            "# Generated by generate_production_config.py": None,
            f"# Robot: {self.robot_id}": None,
            f"# Application: {self.specification.application}": None,
            "# WARNING: Review before deployment": None,
            "": None,
            "robots": {
                self.robot_id: {
                    "# Robot Type": self.specification.robot_type,
                    "# Mass": f"{self.specification.mass} kg",
                    "# Dimensions": self.specification.dimensions,
                    "max_linear_velocity": self.limits.get("max_linear_velocity"),
                    "max_angular_velocity": self.limits.get("max_angular_velocity"),
                    "max_acceleration": self.limits.get("max_acceleration"),
                    "max_deceleration": self.limits.get("max_deceleration"),
                    "workspace_bounds": self.limits.get("workspace_bounds", []),
                    "restricted_zones": [
                        {
                            "name": zone.name,
                            "bounds": zone.bounds,
                            "reason": zone.reason,
                        }
                        for zone in self.zones if zone.zone_type == "restricted"
                    ],
                    "warning_zones": [
                        {
                            "name": zone.name,
                            "bounds": zone.bounds,
                            "reason": zone.reason,
                        }
                        for zone in self.zones if zone.zone_type == "warning"
                    ],
                    "collision_safety_margin": self.limits.get("collision_safety_margin"),
                    "emergency_stop_distance": self.limits.get("emergency_stop_distance"),
                }
            },
            "# Compliance Notes": self.compliance_notes,
            "# Warnings": self.warnings,
        }
        return yaml.dump(data, default_flow_style=False, sort_keys=False)


def interactive_input() -> RobotSpecification:
    """Get robot specification via interactive prompts"""
    
    spec = RobotSpecification()
    
    print("\n" + "="*70)
    print("PRODUCTION SAFETY CONFIGURATION GENERATOR")
    print("="*70)
    print("\nThis tool generates ISO 10218 compliant safety configurations.")
    print("Please answer the following questions about your robot.\n")
    
    # Basic info
    spec.name = input("Robot name/ID: ").strip()
    
    print("\nRobot type:")
    print("  1. Mobile robot (AGV/AMR)")
    print("  2. Manipulator arm")
    print("  3. Drone/UAV")
    print("  4. Humanoid robot")
    choice = input("Select (1-4): ").strip()
    types = {
        "1": "mobile_robot",
        "2": "manipulator",
        "3": "drone",
        "4": "humanoid",
    }
    spec.robot_type = types.get(choice, "mobile_robot")
    
    # Physical specs
    print("\n--- Physical Specifications ---")
    spec.mass = float(input("Robot mass (kg): ") or "10")
    
    print("\nDimensions (meters):")
    spec.dimensions["length"] = float(input("  Length: ") or "0.5")
    spec.dimensions["width"] = float(input("  Width: ") or "0.5")
    spec.dimensions["height"] = float(input("  Height: ") or "0.5")
    
    # Performance specs
    print("\n--- Performance Specifications ---")
    spec.max_linear_velocity = float(input("Max linear velocity (m/s): ") or "1.0")
    spec.max_angular_velocity = float(input("Max angular velocity (rad/s): ") or "1.0")
    spec.max_acceleration = float(input("Max acceleration (m/s²): ") or "1.0")
    spec.max_deceleration = float(input("Max deceleration (m/s²): ") or "2.0")
    
    # Sensors
    print("\n--- Sensors ---")
    print("Select installed sensors (comma-separated numbers):")
    print("  1. LiDAR")
    print("  2. Camera")
    print("  3. Ultrasonic")
    print("  4. Bumpers")
    print("  5. Force/Torque sensor")
    print("  6. IMU")
    sensor_choices = input("Sensors: ").strip().split(",")
    sensor_map = {
        "1": "lidar",
        "2": "camera",
        "3": "ultrasonic",
        "4": "bumpers",
        "5": "force_torque",
        "6": "imu",
    }
    spec.sensor_types = [sensor_map.get(c.strip(), "unknown") for c in sensor_choices if c.strip()]
    
    # Environment
    print("\n--- Environment ---")
    print("  1. Indoor (controlled)")
    print("  2. Outdoor (uncontrolled)")
    print("  3. Mixed")
    env_choice = input("Environment type: ").strip()
    spec.workspace_type = ["indoor", "outdoor", "mixed"][int(env_choice) - 1] if env_choice in ["1", "2", "3"] else "indoor"
    
    # Human interaction
    print("\n--- Human Interaction (ISO/TS 15066) ---")
    print("  1. Separated (fenced workspace)")
    print("  2. Collaborative (shared workspace)")
    print("  3. Hand-guided (direct contact)")
    human_choice = input("Interaction type: ").strip()
    spec.human_proximity = ["separated", "collaborative", "hand_guided"][int(human_choice) - 1] if human_choice in ["1", "2", "3"] else "collaborative"
    
    # Safety hardware
    print("\n--- Safety Hardware ---")
    spec.safety_plc = input("Safety PLC installed? (y/n): ").strip().lower() == "y"
    spec.hardware_estop = input("Hardware E-stop buttons? (y/n): ").strip().lower() == "y"
    spec.light_curtains = input("Light curtains? (y/n): ").strip().lower() == "y"
    spec.force_limiting = input("Force limiting (compliant arm)? (y/n): ").strip().lower() == "y"
    
    # Application
    spec.application = input("\nApplication description: ").strip()
    
    return spec


def calculate_safety_limits(spec: RobotSpecification) -> dict[str, Any]:
    """Calculate safety limits based on specification"""
    
    limits = {}
    
    # Velocity limits with safety margins
    # ISO 10218: Reduce max velocity by 20% for safety margin
    limits["max_linear_velocity"] = round(spec.max_linear_velocity * 0.8, 2)
    limits["max_angular_velocity"] = round(spec.max_angular_velocity * 0.8, 2)
    
    # Acceleration/deceleration
    limits["max_acceleration"] = round(spec.max_acceleration * 0.8, 2)
    limits["max_deceleration"] = spec.max_deceleration  # Keep deceleration high for safety
    
    # Workspace bounds (example: 50m x 50m for outdoor, 20m x 20m for indoor)
    if spec.workspace_type == "outdoor":
        limits["workspace_bounds"] = [
            {"x": -50.0, "y": -50.0},
            {"x": 50.0, "y": -50.0},
            {"x": 50.0, "y": 50.0},
            {"x": -50.0, "y": 50.0},
        ]
    else:
        limits["workspace_bounds"] = [
            {"x": -20.0, "y": -20.0},
            {"x": 20.0, "y": -20.0},
            {"x": 20.0, "y": 20.0},
            {"x": -20.0, "y": 20.0},
        ]
    
    # Safety margins based on robot dimensions and velocity
    # Higher speeds need larger margins
    base_margin = max(spec.dimensions.get("length", 0.5), spec.dimensions.get("width", 0.5))
    velocity_factor = spec.max_linear_velocity / 2.0  # Normalize to 2 m/s
    limits["collision_safety_margin"] = round(base_margin * (1 + velocity_factor), 2)
    
    # Emergency stop distance
    # d = v² / (2a) + safety_margin
    v = spec.max_linear_velocity
    a = spec.max_deceleration
    estop_distance = (v * v) / (2 * a) if a > 0 else 1.0
    limits["emergency_stop_distance"] = round(estop_distance + limits["collision_safety_margin"], 2)
    
    return limits


def generate_safety_zones(spec: RobotSpecification) -> list[SafetyZone]:
    """Generate recommended safety zones"""
    
    zones = []
    
    if spec.human_proximity == "collaborative":
        # Collaborative workspace zone
        zones.append(SafetyZone(
            name="collaborative_workspace",
            zone_type="warning",
            bounds=[
                {"x": -2.0, "y": -2.0},
                {"x": 2.0, "y": -2.0},
                {"x": 2.0, "y": 2.0},
                {"x": -2.0, "y": 2.0},
            ],
            reason="ISO/TS 15066 collaborative workspace - reduced speed required",
        ))
    
    if spec.workspace_type == "indoor":
        # Example: stairs zone
        zones.append(SafetyZone(
            name="stairs",
            zone_type="restricted",
            bounds=[
                {"x": 10.0, "y": 10.0},
                {"x": 12.0, "y": 10.0},
                {"x": 12.0, "y": 12.0},
                {"x": 10.0, "y": 12.0},
            ],
            reason="Stairs - fall hazard",
        ))
    
    return zones


def check_iso_compliance(spec: RobotSpecification, limits: dict) -> tuple[list[str], list[str]]:
    """Check ISO 10218 compliance and return notes and warnings"""
    
    notes = []
    warnings = []
    
    # ISO 10218-1: Robots and robotic devices - Safety requirements for industrial robots
    
    # Check 1: Emergency stop functionality
    if spec.hardware_estop:
        notes.append("✓ Hardware E-stop installed (ISO 10218-1: 5.6)")
    else:
        warnings.append("⚠ Hardware E-stop not detected - REQUIRED by ISO 10218-1: 5.6")
    
    # Check 2: Protective stop
    if "lidar" in spec.sensor_types or "camera" in spec.sensor_types:
        notes.append("✓ Presence sensing for protective stop (ISO 10218-1: 5.10)")
    else:
        warnings.append("⚠ No presence sensing - protective stop may not be effective")
    
    # Check 3: Speed monitoring
    notes.append(f"✓ Speed limits defined: {limits['max_linear_velocity']} m/s (20% safety margin)")
    
    # Check 4: Collaborative operation (ISO/TS 15066)
    if spec.human_proximity == "collaborative":
        if spec.force_limiting:
            notes.append("✓ Force limiting for collaborative operation (ISO/TS 15066)")
        else:
            warnings.append("⚠ Collaborative operation without force limiting - high risk")
        
        if limits["max_linear_velocity"] > 0.5:
            warnings.append("⚠ Collaborative speed exceeds 0.5 m/s recommendation (ISO/TS 15066)")
    
    # Check 5: Workspace limits
    notes.append("✓ Workspace boundaries defined (ISO 10218-1: 5.12)")
    
    # Check 6: Safety PLC
    if spec.safety_plc:
        notes.append("✓ Safety PLC installed for safety-related control")
    else:
        warnings.append("⚠ No safety PLC - consider for SIL-rated safety functions")
    
    # Check 7: Risk assessment
    warnings.append("⚠ Formal risk assessment required before deployment (ISO 10218-1: 4.2)")
    
    return notes, warnings


def print_configuration(config: SafetyConfig) -> None:
    """Print configuration summary"""
    
    print("\n" + "="*70)
    print("GENERATED SAFETY CONFIGURATION")
    print("="*70)
    
    print(f"\nRobot ID: {config.robot_id}")
    print(f"Type: {config.specification.robot_type}")
    print(f"Application: {config.specification.application}")
    
    print("\n--- Safety Limits ---")
    for key, value in config.limits.items():
        print(f"  {key}: {value}")
    
    print("\n--- Safety Zones ---")
    for zone in config.zones:
        print(f"  {zone.name} ({zone.zone_type}): {zone.reason}")
    
    print("\n--- Compliance Notes ---")
    for note in config.compliance_notes:
        print(f"  {note}")
    
    if config.warnings:
        print("\n--- WARNINGS ---")
        for warning in config.warnings:
            print(f"  {warning}")
    
    print("\n" + "="*70)


def main():
    parser = argparse.ArgumentParser(
        description="Generate production safety configuration"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="production_safety_config.yaml",
        help="Output file (default: production_safety_config.yaml)"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output as JSON instead of YAML"
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Use default values (for testing)"
    )
    
    args = parser.parse_args()
    
    # Get robot specification
    if args.non_interactive:
        spec = RobotSpecification(
            name="example_robot",
            robot_type="mobile_robot",
            max_linear_velocity=1.0,
            max_angular_velocity=1.0,
            max_acceleration=1.0,
            max_deceleration=2.0,
            mass=50.0,
            dimensions={"length": 0.8, "width": 0.6, "height": 0.5},
            sensor_types=["lidar", "camera"],
            workspace_type="indoor",
            human_proximity="collaborative",
            application="Warehouse automation",
            safety_plc=True,
            hardware_estop=True,
            light_curtains=False,
            force_limiting=False,
        )
    else:
        spec = interactive_input()
    
    # Generate configuration
    robot_id = spec.name or "robot_01"
    limits = calculate_safety_limits(spec)
    zones = generate_safety_zones(spec)
    notes, warnings = check_iso_compliance(spec, limits)
    
    config = SafetyConfig(
        robot_id=robot_id,
        specification=spec,
        limits=limits,
        zones=zones,
        compliance_notes=notes,
        warnings=warnings,
    )
    
    # Print summary
    print_configuration(config)
    
    # Save configuration
    if args.json:
        output_file = args.output.replace('.yaml', '.json')
        with open(output_file, 'w') as f:
            json.dump({
                "robot_id": config.robot_id,
                "specification": config.specification.__dict__,
                "limits": config.limits,
                "zones": [z.__dict__ for z in config.zones],
                "compliance_notes": config.compliance_notes,
                "warnings": config.warnings,
            }, f, indent=2)
        print(f"\n📄 Configuration saved to: {output_file}")
    else:
        with open(args.output, 'w') as f:
            f.write(config.to_yaml())
        print(f"\n📄 Configuration saved to: {args.output}")
    
    # Final warnings
    if warnings:
        print("\n" + "!"*70)
        print("IMPORTANT: Address all warnings before production deployment!")
        print("!"*70)
        return 1
    else:
        print("\n✅ Configuration ready for review")
        return 0


if __name__ == "__main__":
    exit(main())
