name: Dependabot Auto-Merge

on:
  pull_request:
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f4e4e860b4e9e1c20f8f45a28ed9093b2d3  # v2.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Wait for CI to pass
        uses: lewagon/wait-on-check-action@ccfb013c525c3e8fc9d5a1780d6fd3b9a5c8ad6f  # v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'All Checks Passed'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      
      - name: Auto-approve patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Auto-merge patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
