name: Generate API Docs
on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Generate docs
        run: |
          pip install sphinx
          ./scripts/gen_api_docs.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9cb38e4755a181799308a1a18  # v4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
